### ISSUE TITLE
command not found

### ISSUE THREAD

**Issue by hopewise** [concord-consortium/build-ngspice-js#2]
I've reached Setup, point 4, I did:

```
cd release and run ./build.sh
```

but I got:

```
./build.sh: line 6: emconfigure: command not found
make.sh: line 5: emmake: command not found
mv: rename src/ngspice to src/ngspice.bc: No such file or directory
gen.sh: line 4: emcc: command not found
```

your support is highly appreciated

**Comment by hopewise** [comment]
Although I did:

```
mac:emsdk_portable Apple$ ./emsdk_env.sh
Adding directories to PATH:
PATH += /Users/Apple/Downloads/emsdk_portable
PATH += /Users/Apple/Downloads/emsdk_portable/clang/e1.30.0_64bit
PATH += /Users/Apple/Downloads/emsdk_portable/node/0.12.2_64bit/bin
PATH += /Users/Apple/Downloads/emsdk_portable/emscripten/1.30.0

Setting environment variables:
EMSCRIPTEN = /Users/Apple/Downloads/emsdk_portable/emscripten/1.30.0
```

but it seems that commands still can't be found

**Comment by hopewise** [comment]
ok! I've fixed the path issue, now i get this error: (No module named tools)

```
mac:release Apple$ ./build.sh
~/Documents/projects/dcaclab/ngspice ~/Documents/projects/dcaclab/ngspice/release
Running glibtoolize
glibtoolize: putting auxiliary files in '.'.
glibtoolize: copying file './ltmain.sh'
glibtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
glibtoolize: copying file 'm4/libtool.m4'
glibtoolize: copying file 'm4/ltoptions.m4'
glibtoolize: copying file 'm4/ltsugar.m4'
glibtoolize: copying file 'm4/ltversion.m4'
glibtoolize: copying file 'm4/lt~obsolete.m4'
Running aclocal 
Running autoheader
Running automake -Wall --copy --add-missing
configure.ac:37: installing './compile'
configure.ac:32: installing './missing'
src/Makefile.am: installing './depcomp'
Running autoconf
Success.
patching file configure
Hunk #1 succeeded at 17070 (offset 424 lines).
~/Documents/projects/dcaclab/ngspice/release
Traceback (most recent call last):
  File "/Users/Apple/Downloads/emsdk_portable/emscripten/1.30.0/emconfigure", line 21, in <module>
    from tools import shared
ImportError: No module named tools
Traceback (most recent call last):
  File "/Users/Apple/Downloads/emsdk_portable/emscripten/1.30.0/emmake", line 22, in <module>
    from tools import shared
ImportError: No module named tools
mv: rename src/ngspice to src/ngspice.bc: No such file or directory
Traceback (most recent call last):
  File "/Users/Apple/Downloads/emsdk_portable/emscripten/1.30.0/emcc", line 52, in <module>
    from tools import shared, jsrun, system_libs
ImportError: No module named tools
```

**Comment by hopewise** [comment]
Can you please help us here: http://stackoverflow.com/questions/30603143/importerror-no-module-named-tools
